### Home
GET http://localhost:3000/

### List users
GET http://localhost:3000/users

### Register new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "tester",
  "email": "tester@megah.com",
  "password": "megah-property-creator"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "tester@megah.com",
  "password": "megah-property-creator"
}

### Logout
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0ZXIiLCJlbWFpbCI6InRlc3RlckBtZWdhaC5jb20iLCJpYXQiOjE2MDM3MjY2MDMsImV4cCI6MTYwMzk4NTgwM30.IqsQujCqlu-b9g4rW4k5m4hzcs7uY44jufVW8JrnCqA

### Get authenticated user data
GET http://localhost:3000/auth/tester
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0ZXIiLCJlbWFpbCI6InRlc3RlckBtZWdhaC5jb20iLCJpYXQiOjE2MDM3MjY2MDMsImV4cCI6MTYwMzk4NTgwM30.IqsQujCqlu-b9g4rW4k5m4hzcs7uY44jufVW8JrnCqA


### Get list of items
GET http://localhost:3000/items
X-API-Key: megah-property-api-key

### Post array of items
POST http://localhost:3000/items
X-API-Key: megah-property-api-key
Content-Type: application/json

{
  "items": [
    {"item": "Rumah Pohon", "userId": 1},
    {"item": "Studio Musik", "userId": 3},
    {"item": "McDonalds", "userId": 9}
  ]
}